---
title: "Week 3 Assignment"
author: "Nick Orka"
date: "3/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=F, message=F)
library(readr)
library(plotly)
library(tidyr)
library(dplyr)
```
## Overview 

This is coronavirus COVID-19 update based on data collected by John Hopkins CSSE.  
https://github.com/CSSEGISandData/COVID-19

```{r, echo=F}
confUrl = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv"
dailyPath <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/"
confDF <- read_csv(confUrl)
lastDate <- max(as.Date(names(confDF)[5:length(confDF)], "%m/%d/%y"))
dateField <- as.character.Date(lastDate, "%m-%d-%Y")
dailyUrl <- paste0(dailyPath, dateField, ".csv")
df <- read_csv(dailyUrl)
df <- df %>%
    mutate(location = sub(", NA", "", paste(`Country/Region`, `Province/State`, sep = ", "))) %>%
    mutate(confPopup = paste0(location, "<br>Confirmed = ", Confirmed,
                              "<br>Deaths = ", Deaths,
                              "<br>Recovered = ", Recovered))
 

mapDF <- df[, c("Longitude", "Latitude", "Confirmed")]
  
m <- plot_ly(df, x = ~Longitude, 
              y = ~Latitude,
              z = ~Confirmed,
             color = ~`Country/Region`,
             text = ~confPopup
             ) %>%
  add_markers() %>%
  layout(title = "Corona virus by location")
```
#### This is just a stupid requirement for the date = `r format(lastDate - 62, "%B %d, %Y")`
## Data for **`r format(lastDate, "%B %d, %Y")`**
```{r, echo=F, cache=F, fig.width=10, warning=F, message=F}
m
```

